const starterContacts = [
    {
      firstname: "Ismael",
      lastname: "Sherif",
      contact_type: "Owner",
      email: "isherif@nonya.com",
      phone: "310-213-0001",
      last_contact_dt: '2023/06/23',
    },
    {
      firstname: "Abel",
      lastname: "Gomez",
      contact_type: "Owner",
      email: "agomez@nonya.com",
      phone: "310-999-0001",
      last_contact_dt: '2023/07/23',
    },
    {
      firstname: "Michael",
      lastname: "Aboda",
      contact_type: "Owner",
      email: "maboda64@gmail.com",
      phone: "310-999-4401",
      last_contact_dt: '2023/07/23',
    },
    {
        firstname: "Patricia",
        lastname: "Grey",
        contact_type: "Owner",
        email: "",
        phone: "",
        last_contact_dt: '2024/02/23',
      },
      {
        firstname: "Bruno",
        lastname: "Mars",
        contact_type: "Owner",
        email: "bmars@nonya.com",
        phone: "310-213-0881",
        last_contact_dt: '202/06/01',
      },
      {
        firstname: "Jeremy",
        lastname: "White",
        contact_type: "Owner",
        email: "jwhite@nonya.com",
        phone: "310-988-0001",
        last_contact_dt: '2023/08/23',
      },
      {
        firstname: "Lex",
        lastname: "Johnson",
        contact_type: "Owner",
        email: "ljohnson4@gmail.com",
        phone: "310-922-4401",
        last_contact_dt: '2024/03/10',
      },
      {
          firstname: "Ariella",
          lastname: "Santos",
          contact_type: "Owner",
          email: "",
          phone: "",
          last_contact_dt: '2024/02/23',
        },
  ]
  module.exports = starterContacts